#! /bin/sh
### BEGIN INIT INFO
# Provides:          libki-server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run Libki server
# Description: Start and stop the libki-server Docker Compose app.
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

cd /var/libki/app

case "$1" in
  start)
    docker-compose up &
    ;;
  restart|force-reload|reload)
    docker-compose restart &
    ;;
  stop)
    docker-compose stop &
    ;;
  status)
    docker-compose ps
    ;;
  *)
    echo "Usage: /etc/init.d/libki {start|stop|restart|force-reload|reload}"
    exit 2
    ;;
esac

exit 0
