package Libki::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Libki::Schema::DB',
    connect_info => {
        cursor_class => q{DBIx::Class::Cursor::Cached},
    }
);

=head1 NAME

Libki::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Libki>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Libki::Schema::DB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Kyle M Hall <kyle@kylehall.info>

=head1 LICENSE

This file is part of Libki.

Libki is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as 
published by the Free Software Foundation, either version 3 of
the License, or (at your option) any later version.

Libki is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Libki.  If not, see <http://www.gnu.org/licenses/>.
                                                
=cut

1;
